baseurl = "https://jonthelaion.netlify.com"
title = "your-site-name"
languageCode = "ko-KR"

theme = "R/jonthelaion_website/themes/hugo-hello-programmer-theme"
themesdir = "../.."

paginate = 7

disqusShortname = "jonthelaion"
googleAnalytics = "UA-XXXXXXXX-X"

[author]
    name = "jonthelaion"
    email = "your-email"
