---
title: R Resources
author: jonthelaion
date: '2018-03-31 21:53:00'
slug: r-resources
categories:
  - R
  - resources
tags:
  - R
  - resources
---

#### Blogs
- <a href="https://mathbabe.org/" target="_blank">Cathy O'Neil Blog</a>
- <a href="https://www.datasciencecentral.com/" target="_blank">Data Science Central</a>
- http://www.bytemining.com/
- http://www.datascience.university/

#### Online Courses
- <a href="https://medium.freecodecamp.org/every-single-machine-learning-course-on-the-internet-ranked-by-your-reviews-3c4a7b8026c0" target="_blank">List of Machine Learning Courses</a>
- <a href="https://www.edx.org/professional-certificate/berkeleyx-foundations-of-data-science#courses" target="_blank">BerkeleyX - Foundations of Data Science</a>
- Coursera - John Hopkin's University - Data Science Specialisation
  - The Data Scientists's Toolbox (Complete)
  - R Programming
  - Getting and Cleaning Data
  - Exploratory Data Analysis
  - Reproducible Research
  - Statistical Inference
  - Regression Models
  - Practical Machine Learning
  - Developing Data Products

#### R Markdown
- <a href="https://bookdown.org/yihui/blogdown/" target="_blank">Creating Websites with R Markdown</a> (Currently Reading)
- <a href="http://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf" target="_blank">R Markdown Reference Guide</a>
- <a href="https://en.wikibooks.org/wiki/LaTeX/Mathematics" target="_blank">LaTeX</a>

#### General Data Science
- Doing Data Science
- <a href="https://columbia-applied-data-science.github.io/appdatasci.pdf" target="_blank">Columbia - Applied Data Science</a>

#### Data for Good Initiatives
- <a href="https://www.drivendata.org/" target="_blank">Driven Data</a>
- <a href="http://www.datakind.org/" target="_blank">Data Kind</a>

#### Learning R
- The Art of R Programming - Norman Matloff (No Starch Press)
- R for Everyone: Advanced Analytics and Graphics - Jared Lander (Addison-Wesley)
- R in a Nutshell - Joseph Adler (O'Reilly)

#### Learning Python
- Learning Python - Mark Lutz and David Ascher (O'Reilly)
- Python for Data Analysis - Wes McKinney (O'Reilly)

#### Math
- Linear Algebra and Its Applications - Gilbert Strang (Cengage Learning)
- Convex Optimization - Stephen Boyd and Lieven Vandenberghe (Cambridge University Press)
- A First Course in Probability - Sheldon Ross (Academic Press)
- A career in statistics: beyond the numbers - Gerald J. Hahn and Necip Doganaksoy

#### Data Analysis and Statistical Inference
- Statistical Inference - George Casella and Roger L. Berger (Cengage Learning)
- Bayesian Data Analysis - Andrew Gelman (Chapman & Hall)
- Data Analysis Using Regression and Multilevel/Hierarchical Models - Andrew Gelman and Jennifer Hall (Cambridge University Press)
- <a href="http://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/" target="_blank">Advanced Data Analysis from an Elementary Point of View - Cosma Shalizi </a> (under contract with Cambridge University Press)
- The Elements of Statistical Learning: Data Mining, Inference and Prediction - Trevor Hastie, Robert Tibshirani and Jerome Friedman (Springer)

#### Visualisation
- The Elements of Grpahing Data - William Cleveland (Hobart Press)
- Visualize This: The FLowingData Guide to Design, Visualization, and Statistics - Nathan Yau (Wiley)
- The VIsual Display of Quantitative Information - Edward Tufte (Graphics Press)
- https://rpubs.com/gjeffroy/ggplotportfolio

#### Artificial Intelligence and Machine Learning
- Pattern Recognition and Machine Learning - Christopher Bishop (Springer)
- Bayesian Reasoning and Machine Learning - David Barber (Cambridge University Press)
- Programming COllective Intelligence - Toby Segaran (O'Reilly)
- Artificial Intelligence: A Modern Approach - Stuart Russell and Peter Norvig (Prentice Hall)
- Foundations of Machine Learning - Mehryar Mohri, Afshin Rostamizadeh and Ameet Talwalkar (MIT Press)
- Introduction to Machine Learning (Adaptive COmputation and Machine Learning) - Ethem Alpaydin (MIT Press)

#### Experimental Design
- Field Experiments - Alan S. Gerber and Donald P. Green (Norton)
- Statistics for Experimenters: Design, Innovation, and Discovery - George E. P. Box (Wiley-Interscience)