---
title: Hello World
author: jonthelaion
date: '2018-03-31 20:33:00'
slug: hello-world
categories: []
tags: []
---

Creating this blog to journal my progress towards becoming ~~a data scientist~~ an applied statistician. While my interest in this field was initially piqued by the data science hype train, I feel that my view of this discipline is more closely aligned with the traditional school of applied statistics, rather than the newer "hacker-culture" school of data science. I hope that one day I can learn enough about the art of working with data in an imperfect and uncertain world to be able to use modern statistical techniques and make a positive contribution to society. 

The other appeal of working in the field of statistics / data science is that the skills gained are industry-agnostic and presents me with the opportunity to work in a variety of fields. Examples of some areas that are personally meaningful to me include:

- education and learning analytics;
- mental health;
- aged care and the elderly;
- minorities and equality;
- crime and justice.