---
title: Building Web Applications in R with Shiny (Datacamp)
author: jonthelaion
date: '2018-04-19 07:04:00'
slug: building-web-applications-in-r-with-shiny-datacamp
output: html_document
runtime: shiny
categories:
  - datacamp
  - datascience
  - dataviz
  - R
  - shiny
tags:
  - datacamp
  - datascience
  - dataviz
  - R
  - shiny
---

# Helpful Links

- www.rstudio.com/resources/cheatsheets
- shiny.rstudio.com

# Tips

- Always run the entire script; not just at the point that you are developing code
- Sometimes the best way to troubleshoot is to run your code and then review errors
- Watch out for commas!

# Anatomy of a Shiny App


## Example: Shiny App


```{r}
library(shiny)
library(ggplot2)
library(dplyr)
library(DT)
load("../../data/movies.Rdata")
```


## Example: Calendar app

```{r}
min_date <- min(movies$thtr_rel_date)
max_date <- max(movies$thtr_rel_date)

# UI
ui <- fluidPage(
    sidebarLayout(

    # Input(s)
    sidebarPanel(

      # Explanatory text
      HTML(paste0("Movies released between the following dates will be plotted.
                  Pick dates between ", min_date, " and ", max_date, ".")),

      # Break for visual separation
      br(), br(),

      # Date input
      dateRangeInput(inputId = "date",
                label = "Select dates:",
                start = "2013-01-01",
                end = "2014-01-01",
                min = min_date,
                max = max_date,
                startview = "year")
    ),

    # Output(s)
    mainPanel(
      plotOutput(outputId = "scatterplot")
    )
  )
)

# Server
server <- function(input, output) {

  # Create the plot
  output$scatterplot <- renderPlot({
    req(input$date)
    movies_selected_date <- movies %>%
      filter(thtr_rel_date >= as.POSIXct(input$date[1]) & thtr_rel_date <= as.POSIXct(input$date[2]))
    ggplot(data = movies_selected_date, aes(x = critics_score, y = audience_score, color = mpaa_rating)) +
      geom_point()
  })

}
# Create a Shiny app object
shinyApp(ui = ui, server = server)
```

