---
title: Shiny App Example - Simple
author: jonthelaion
date: '2018-04-19'
slug: shiny-app-example-simple
output: html_document
runtime: shiny
categories:
  - R
  - shiny
tags:
  - R
  - shiny
---

```{r}
library(shiny)
library(ggplot2)
library(dplyr)
library(DT)
load("../../data/movies.Rdata")
```


```{r}
# Define UI for application that plots features of movies 
ui <- fluidPage(
  
  # Sidebar layout with a input and output definitions 
  sidebarLayout(
    
    # Inputs
    sidebarPanel(
      
      # Select variable for y-axis
      selectInput(inputId = "y", 
                  label = "Y-axis:",
                  choices = c("imdb_rating", "imdb_num_votes", "critics_score", "audience_score", "runtime"), 
                  selected = "imdb_rating"),
      # Select variable for x-axis
      selectInput(inputId = "x", 
                  label = "X-axis:",
                  choices = c("imdb_rating", "imdb_num_votes", "critics_score", "audience_score", "runtime"), 
                  selected = "imdb_num_votes"),
      # Set alpha level
      sliderInput(inputId = "alpha", 
                  label = "Alpha:", 
                  min = 0, max = 1, 
                  value = 0.5)
    ),
    # Outputs
    mainPanel(
      plotOutput(outputId = "scatterplot", height = 200), plotOutput(outputId = "density", height = 200)
    )
  )
)

# Define server function required to create the scatterplot
server <- function(input, output) {

  # Create scatterplot object the plotOutput function is expecting
  output$scatterplot <- renderPlot({
    ggplot(data = movies, aes_string(x = input$x, y = input$y)) +
      geom_point(alpha = input$alpha)
  })
  # Create scatterplot object the plotOutput function is expecting
  output$density <- renderPlot({
    ggplot(data = movies, aes_string(x = input$x)) +
      geom_density()
  })
}

# Create a Shiny app object
shinyApp(ui = ui, server = server)
```
